apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-gen-script
  namespace: cloudarena-system
data:
  traffic_loop.sh: |
    #!/bin/sh
    TARGET="http://backend-service.cloudarena-app.svc.cluster.local:8080/api/data"
    echo "Traffic generator starting target: $TARGET"

    RATE_SLEEP=1.0

    while true; do
      CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 2 --max-time 3 "$TARGET" || echo "000")
      TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
      if [ "$CODE" = "200" ]; then
        echo "[$TIMESTAMP] OK ($CODE) -> $TARGET"
      else
        echo "[$TIMESTAMP] FAIL ($CODE) -> $TARGET"
      fi
      sleep "$RATE_SLEEP"
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-gen
  namespace: cloudarena-system
  labels:
    app.kubernetes.io/name: traffic-gen
    cloudarena.io/role: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traffic-gen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traffic-gen
    spec:
      containers:
      - name: loadgen
        image: curlimages/curl:8.7.1
        command: ["/bin/sh", "/scripts/traffic_loop.sh"]
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: script-vol
          mountPath: /scripts
      volumes:
      - name: script-vol
        configMap:
          name: traffic-gen-script
          defaultMode: 0755
