apiVersion: v1
kind: Namespace
metadata:
  name: cloudarena-app
  labels:
    cloudarena.io/environment: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudarena-system
  labels:
    cloudarena.io/environment: system
